# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_backgroundprocess_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundprocess',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backgroundprocess',
            name='stopped_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='backgroundprocess',
            name='terminate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='cmd_path',
            field=models.CharField(default=b'/home/yay2/run', max_length=2048),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='log_path',
            field=models.CharField(default=b'/tmp', max_length=2048),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='mount_path',
            field=models.CharField(default=b'/mnt', max_length=2048),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='playlist_path',
            field=models.CharField(default=b'/home/yay2/playlists', max_length=2048),
        ),
    ]
