# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_auto_20160413_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundprocess',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
