# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_backgroundprocess_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundprocess',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
